version: 2
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: "~/braspag/braspag/"
    steps:
      - checkout
      - restore_cache:
          keys:
            - pip-{{ .Branch }}
            - pip-master
      - run:
          name: Install Dependencies
          command: |
              pip install -r requirements/base.txt
              pip install -r requirements/test.txt
      - save_cache:
          key: pip-{{ .Branch }}
          paths:
            - "~/.cache/pip"
      - run:
          name: Run Tests
          command: make test
